server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ras_music?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update   # hoặc validate / create-drop tùy nhu cầu
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    cors:
      mappings:
        "[/api/**]":
          allowed-origins: "http://localhost:5173"
          allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true

app:
  upload:
    dir: uploads
  public-base-url: http://localhost:8080
    
logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    